[build]
builder = "heroku/buildpacks:20"

[build.buildpacks]
url = "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"

[[build.buildpacks]]
url = "heroku/nodejs"

[build.env]
NODE_ENV = "production"

[deploy]
startCommand = "node server.js"
